spring:
  application:
    name: item-microservice

  datasource:
    url: jdbc:mysql://localhost:3306/taskdb
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 3000